var quesandans={
    "subject1" : {
  "question1" : ["What is the FULL definition of chromosome","in the nucleus", "both a and c","a thread like structure in the nucleus of a cell","a piece of rope that looks like a thread",'3'],
  "question2" : ["What is the theory of Darwin?" , "Darwin believed in Natural Selection", "Darwin believed that animals have to need something to evolved","Ecology Structure is a Part of the theory of evolution","all of the above",'4'],
  "question3" : ["Who invented the BALLPOINT PEN?" , "Biro Brothers","Waterman Brothers","Bicc Brothers","Hemanth Reddy",'1'],
  "question4" : ["Who invented Jet Engine?" , "Sir Frank Whittle","Gottlieb Daimler","Abhinay Bali","Lewis E Waterman",'1'],
  "question5" : ["What invention caused many deaths while testing it?" , "Dynamite","Ladders","Race cars","Parachute",'4'],
  "question6" : ["For whom high heeled shoes were invented?" , "Cleopatra","Queen Elizabeth I","King Louis the XIV","King Charles II",'3'],
  "question7" : ["What item, originally called the 'Whirlwind', was invented by Ives McGaffey in 1869?" , "Blender","Electric mixer","Washing machine","Vacuum cleaner",'4'],
  "question8" : ["Where were wigs first invented?" , "Japan","France","Egypt","China",'3'],
  "question9" : ["What Galileo invented?" , "Barometer","Pendulem clock","Microscope","Thermometer",'4'],
  "question10" :["Who is the English physicist responsible for the 'Big Bang Theory'?" , "Albert Einstein","Michael Skube","George Gamow","Roger Penrose",'3'],
  "question11" :["What 'game' was first produced by the Southern Novelty Company in Baltimore, Maryland in 1892?" , "Frisbee","Monopoly","Ouija board","Ping Pong",'3'],  
  "question12" : ["Who had an explosive idea and first patented DYNAMITE?" , "J. R. Gluber","Abhinay Bali","G. Fawks","W. Bickford",'2'],
  "question13" : ["Which American inventor invented the commercial telegraph, based on Joseph Henry's work?" ,  "Alexander Graham Bell","Samuel Morse","Sir James DeWar","Hemanth Reddy",'2'],
  "question14" : ["What was the first message sent by his telegraph machine?" , "Save our Souls", "Vote Whip", "What has God Wrought","Mr Watson! Come Here",'3'],
  "question15" : ["What famous invention of the 15th century made reading possible for the general public?" ,  "Printing Press", "Typewriter", "Spectacles", "Public Library",'1'],
  "question16" : ["In 1937, what Canadian invention helped people get around in winter?" , "Toboggan","Snow Board","Snow mobile","Ski Chair Lift",'3'],
  "question17" : ["Who invented the World Wide Web?" ,  "Microsoft","Google","A laboratory in switzerland","Apple",'3'],
  "question18" : ["Which one of the following records the distance travelled by a vehicle?" , "Manometer","Odometer","Speedometer","Motometer",'2'],
  "question19" :["Which scientist discovered the radioactive element radium?" , "Isaac Newton","Albert Einstein","Benjamin Franklin","Marie Curie",'4'],
  "question20" :["CORN FLAKES - Who made them first?" , "Nabisco","Kellogg","Quaker","Archers",'2']
    },
   "subject2" : {
  "question1" : ["Which of the following is not required in an email address?" , "C0694853","Full name","symbol","Domain name",'2'],
"question2" : ["The word 'source' in open source refers to what?" , "Developer source","Platform source","Source code","Source port",'3'],
"question3" : ["Which of the following programs requires a runtime environment?" , "Java applet" ,"Windows executable","macOS application","iOS app",'1' ],
"question4" : ["What unit of measurement is equal to 1,000 cycles per second? " , "Kilohertz" ,"Megahertz","Megabyte","Kibibyte",'1'],
"question5" : ["What is another name for a password that contains multiple words?" , "Passcode","Passwordle","Passphrase" ,"Passtring",'3'],
"question6" : ["Which of the following components is most commonly overclocked?" , "CPU","SSD","HDD","Monitor",'1'],
"question7" : ["What is the maximum number of devices in a piconet?" , "8","64","256","512",'1' ],
"question8" : ["Apple's 'Tiger' OS immediately followed which version?" ,"Panther","Jaguar","Puma","Cheetah",'1' ],
"question9" : ["What verb is used to describe checking for information in a database?" , "Querying","Digging","Pulling","Peeking",'1'],
"question10" :  ["What is a technical term for the person in charge of maintaining a website?" , "Web host","Web leader","Webmaster","Webposter",'3'],
"question11" :  ["An exponent in a mathematical equation is an example of what?" , "Postscript","Typescript","Subscript","Superscript",'4'],
"question12" : ["Which of the following is not a telecommunications device?" , "TV","Radio","DVD player","Cell phone",'3'],
"question13" : ["What type of information does the WHOIS service provide?" , "Personal phone numbers","Business financial records","Domain name registration info" ,"Email addresses",'3'],
"question14" : ["What is the largest volume size supported by the FAT32 file system?" , "2 terabytes" ,"8 terabytes","32 terabytes","64 terabytes",'1'],
"question15" : ["To what does the 32 in the 'Win32' API refer?" , "Colors","Platforms","Programs","Bits",'4'],
"question16" : ["What media provider offers a paid streaming service called 'Red?'" , "Spotify","Pandora","YouTube","Vimeo",'3'],
"question17" : [ "A SYN flood is a type of what computer attack?", "Denial of service" ,"Trojan horse","Rootkit","Virus",'1'],
"question18" : ["A program value that does not change is also called what?" ," Variable","Function","Constant","Operator",'3'],
"question19" : ["What adjective best describes a software program that supports plugins?" , "Scalable","Extensible","Portable","Flexible",'1'],
"question20" : ["What type of hardware device may experience fragmentation over time?" , "CPU","GPU","RAM","HDD",'1']
    }
};
